use-configs:
  - lint/opensource/copyrights
  - lint/opensource/banned_words
lint:
  clang-format:
   included:
      - \.cpp$
      - \.h$
      - \.inl$
      - \.inc$
      - \.hpp$
   excluded:
      - third_party/
      - scripts/
      - generated

  cmake-format:
    included:
      - CMakeLists.txt$
      - \.cmake$
    excluded:
      - third_party/*

  python:
    included:
      - \.py$
    venv_name: cal

  copyright:
    excluded:
      - third_party/
      - shared/ocl_slim_def.h
    mit_header:
      year_constraints:
        _default: 2022

  ults-needed:
    disabled: true

  banned_words:
    exclude:
      - third_party/
    main:
      todo:
      wa:
      workaround:
        exclude:
          - third_party/