lint:
  clang-format:
   included:
      - \.cpp$
      - \.h$
      - \.inl$
      - \.inc$
      - \.hpp$
   excluded:
      - third_party/
      - scripts/
      - generated

  cmake-format:
    included:
      - CMakeLists.txt$
      - \.cmake$
    excluded:
      - third_party/*

  copyright:
    excluded:
      - third_party/
      - shared/ocl_slim_def.h
    mit_header:
      contents: |
        {comment_begin}
        {comment_char} Copyright (C) %s Intel Corporation
        {comment_char}
        {comment_char} SPDX-License-Identifier: MIT
        {comment_end}
      year_pattern: (\d+)(-\d+)?
      year_constraints:
        _default: 2022
      file_types:
        cpp:
          includes:
            - \.cpp$
            - \.h$
            - \.inl$
            - \.hpp$
            - \.cl$
            - \.m$
            - \.h.in$
            - \.rc.in$
            - ^Jenkinsfile$
          comment_begin: "/*"
          comment_end: |1
            *
            */
          comment_char: " *"
        bash:
          includes:
            - CMakeLists.txt$
            - \.cmake$
            - \.py$
            - \.sh$
          comment_begin: "#"
          comment_end: "#"
          comment_char: "#"

  ults-needed:
    disabled: true

  banned_words:
    exclude:
      - third_party/
    main:
      todo:
      wa:
      workaround:
